class Galleryphoto
  include Mongoid::Document
  store_in collection: :galleryphoto
  field :el_gallery_blurb
  field :el_gallery_categories_1_path
  field :el_gallery_categories_2_path
  field :el_gallery_categories_3_path
  field :el_gallery_categories_4_path
  field :el_gallery_comment_status
  field :el_gallery_creation_date
  field :el_gallery_id
  field :el_gallery_is_static
  field :el_gallery_mp3_credit
  field :el_gallery_mp3_link
  field :el_gallery_mp3_url
  field :el_gallery_name
  field :el_gallery_originating_site_domain
  field :el_gallery_sites_1_domain
  field :el_gallery_slug
  field :el_gallery_status
  field :el_gallery_template_prefix
  field :el_id
  field :el_order
  field :el_pause
  field :el_photo_caption
  field :el_photo_categories_1_path
  field :el_photo_categories_2_path
  field :el_photo_categories_3_path
  field :el_photo_categories_4_path
  field :el_photo_categories_5_path
  field :el_photo_comment_status
  field :el_photo_creation_date
  field :el_photo_credit
  field :el_photo_height
  field :el_photo_id
  field :el_photo_one_off_photographer
  field :el_photo_photo
  field :el_photo_photo_type_credit
  field :el_photo_photo_type_id
  field :el_photo_photo_type_name
  field :el_photo_photo_type_slug
  field :el_photo_photographer_first_name
  field :el_photo_photographer_last_name
  field :el_photo_photographer_records_audioclips
  field :el_photo_pub_date
  field :el_photo_reproduction_allowed
  field :el_photo_status
  field :el_photo_user_generated
  field :el_photo_width
end
