class Storyinlinemapping
  include Mongoid::Document
  store_in collection: :storyinlinemapping
  field :el_id
  field :el_inline_type
  field :el_object_id
  field :el_story_bylines_1_first_name
  field :el_story_bylines_1_last_name
  field :el_story_bylines_1_records_audioclips
  field :el_story_bylines_2_first_name
  field :el_story_bylines_2_last_name
  field :el_story_bylines_2_records_audioclips
  field :el_story_bylines_3_first_name
  field :el_story_bylines_3_last_name
  field :el_story_bylines_3_records_audioclips
  field :el_story_bylines_4_first_name
  field :el_story_bylines_4_last_name
  field :el_story_bylines_4_records_audioclips
  field :el_story_categories_1_path
  field :el_story_categories_2_path
  field :el_story_categories_3_path
  field :el_story_categories_4_path
  field :el_story_categories_5_path
  field :el_story_categories_6_path
  field :el_story_comment_status
  field :el_story_headline
  field :el_story_id
  field :el_story_lead_photo_cropped_height
  field :el_story_lead_photo_cropped_photo
  field :el_story_lead_photo_cropped_width
  field :el_story_lead_photo_has_headline
  field :el_story_lead_photo_id
  field :el_story_lead_photo_original_caption
  field :el_story_lead_photo_original_categories_1_path
  field :el_story_lead_photo_original_categories_2_path
  field :el_story_lead_photo_original_categories_3_path
  field :el_story_lead_photo_original_categories_4_path
  field :el_story_lead_photo_original_categories_5_path
  field :el_story_lead_photo_original_comment_status
  field :el_story_lead_photo_original_creation_date
  field :el_story_lead_photo_original_credit
  field :el_story_lead_photo_original_height
  field :el_story_lead_photo_original_id
  field :el_story_lead_photo_original_one_off_photographer
  field :el_story_lead_photo_original_photo
  field :el_story_lead_photo_original_photo_type_credit
  field :el_story_lead_photo_original_photo_type_id
  field :el_story_lead_photo_original_photo_type_name
  field :el_story_lead_photo_original_photo_type_slug
  field :el_story_lead_photo_original_photographer_first_name
  field :el_story_lead_photo_original_photographer_last_name
  field :el_story_lead_photo_original_photographer_records_audioclips
  field :el_story_lead_photo_original_pub_date
  field :el_story_lead_photo_original_reproduction_allowed
  field :el_story_lead_photo_original_status
  field :el_story_lead_photo_original_user_generated
  field :el_story_lead_photo_original_width
  field :el_story_metadata_1_content
  field :el_story_metadata_1_content_type_name
  field :el_story_metadata_1_id
  field :el_story_metadata_1_object_id
  field :el_story_metadata_1_type_id
  field :el_story_metadata_1_type_label
  field :el_story_metadata_1_type_name
  field :el_story_metadata_2_content
  field :el_story_metadata_2_content_type_name
  field :el_story_metadata_2_id
  field :el_story_metadata_2_object_id
  field :el_story_metadata_2_type_id
  field :el_story_metadata_2_type_label
  field :el_story_metadata_2_type_name
  field :el_story_one_off_byline
  field :el_story_post_story_blurb
  field :el_story_pre_story_blurb
  field :el_story_print_date
  field :el_story_print_edition_name
  field :el_story_print_headline
  field :el_story_print_page
  field :el_story_print_section_name
  field :el_story_pub_date
  field :el_story_sites_1_domain
  field :el_story_slug
  field :el_story_status
  field :el_story_story
  field :el_story_subhead
  field :el_story_tease
  field :el_story_tease_photo
  field :el_story_update_date
  field :el_story_updated
end
