CATEGORY_TABLE = {
	"/Blogs/Cross Campus/Sports" => [ "cat", "Sports", "cross-campus" ],
	"/Blogs/Sports" => [ "cat", "Sports", "cross-campus" ],
	"/Blogs/Cross Campus/City" => [ "cat", "City", "cross-campus" ],
	"/Blogs/Cross Campus/Crime" => [ "tag", "Crime", "cross-campus" ],
	"/Blogs/News/City News" => [ "cat", "City", "cross-campus" ],
	"/Blogs/Cross Campus/Academics" => [ "tag", "Academics", "cross-campus" ],
	"/Blogs/Cross Campus/University" => [ "cat", "University", "cross-campus" ],
	"/Blogs/News/University News" => [ "cat", "University", "cross-campus" ],
	"/News/University" => [ "cat", "University", "main" ],
	"/News/University News" => [ "cat", "University", "main" ],
	"/Blogs/Cross Campus/Sports/Football" => [ [ "tag", "Football", "cross-campus" ],
                                             [ "cat", "Sports", "cross-campus" ] ],
	"/Sports" => [ "cat", "Sports", "main" ],
	"/Sports/Fall Sports/M. Crew" => [ [ "tag", "M. Crew", "main" ],
                                     [ "cat", "Sports: Fall Sports", "main" ] ],
	"/Sports/Fall Sports/W. Crew" => [ [ "tag", "W. Crew", "main" ],
                                     [ "cat", "Sports: Fall Sports", "main" ] ],
	"/Blogs/Cross Campus/Politics" => [ "tag", "Politics", "cross-campus" ],
	"/Blogs/Cross Campus/City/Nightlife" => [ "tag", "Nightlife", "cross-campus" ],
	"/Blogs/Cross Campus/City/Restaurants" => [ "tag", "Restaurants", "cross-campus" ],
	"/Blogs/Cross Campus/Town-gown" => [ "tag", "Town-gown", "cross-campus" ],
	"/Blogs/Cross Campus/Obituary" => [ "tag", "Obituary", "cross-campus" ],
	"/Opinion" => [ "cat", "Opinion", "main" ],
	"/Opinion/The News' Views" => [ "cat", "Opinion: The News' Views", "main" ],
	"/Blogs/Cross Campus" => [ "", "", "cross-campus" ],
	"/Blogs/Cross Campus/Opinion" => [ "cat", "Opinion", "cross-campus" ],
	"/Blogs/Cross Campus/Culture" => [ "cat", "Culture", "cross-campus" ],
	"/Blogs/Cross Campus/Athletics" => [ "tag", "Athletics", "cross-campus" ],
	"/Sports/Coed Sailing" => [ [ "tag", "Coed Sailing", "main" ],
                              [ "cat", "Sports", "main" ] ],
	"/Blogs/Cross Campus/Money" => [ "tag", "Money", "cross-campus" ],
	"/Scene" => [ "tag", "Scene", "main" ],
	"/Blogs" => [ "", "", "cross-campus" ],
	"/Blogs/Boola Boola" => [ "cat", "Sports", "cross-campus" ],
	"/News/City" => [ "cat", "City", "main" ],
	"/News/City News" => [ "cat", "City", "main" ],
	"/Blogs/Cross Campus/Technology" => [ "tag", "Technology", "cross-campus" ],
	"/Blogs/Cross Campus/City/Elections" => [ ["tag", "Elections", "cross-campus" ],
                                            ["cat", "City", "cross-campus" ] ],
	"/Blogs/Cross Campus/Cops" => [ "tag", "Cops", "cross-campus" ],
	"/Magazine" => [ "", "", "magazine" ],
	"/WEEKEND" => [ "", "", "weekend" ],
	"/WEEKEND/Feature" => [ "cat", "Feature", "weekend" ],
	"/WEEKEND/Music" => [ "tag", "Music", "weekend" ],
	"/WEEKEND/Performance" => [ "tag", "Performance", "weekend" ],
	"/Blogs/Cross Campus/XC" => [ "", "", "cross-campus" ],
	"/News/Features" => [ "cat", "Features", "main" ],
	"/Opinion/Guest Columns" => [ "cat", "Opinion: Guest Columns", "main" ],
	"/Opinion/Staff Columns" => [ "cat", "Opinion: Staff Columns", "main" ],
	"/News/Culture" => [ "cat", "Culture", "main" ],
	"/Sports/Spring Sports/Baseball" => [ ["tag", "Baseball", "main" ],
                                        ["cat", "Sports: Spring Sports", "main" ] ],
	"/Sports/Spring Sports/Softball" => [ ["tag", "Softball", "main" ],
                                        ["cat", "Sports: Spring Sports", "main" ] ],
	"/Sports/Fall Sports/W. Golf" => [ ["tag", "W. Golf", "main" ],
                                     ["cat", "Sports: Fall Sports", "main" ] ],
	"/News/Sci-Tech" => [ "cat", "Sci-Tech", "main" ],
	"/Blogs/Cross Campus/Science" => [ "tag", "Science", "cross-campus" ],
	"/Blogs/Cross Campus/The Buzz" => [ "tag", "The Buzz", "cross-campus" ],
	"/Blogs/Cross Campus/Movies" => [ "tag", "Movies", "cross-campus" ],
	"/Blogs/Cross Campus/Spring Fling" => [ "tag", "Spring Fling", "cross-campus" ],
	"/Blogs/Cross Campus/WEEKEND" => [ "cat", "WEEKEND", "cross-campus" ],
	"/Blogs/Cross Campus/Through the Lens" => [ "tag", "Through the Lens", "cross-campus" ],
	"/WEEKEND/Blog" => [ "cat", "Blog", "weekend" ],
	"/Sports/Spring Sports/W. Tennis" => [ ["tag", "W. Tennis", "main" ],
                                         ["cat", "Sports: Spring Sports", "main" ] ],
	"/Sports/Spring Sports/W. Lacrosse" => [ ["tag", "W. Lacrosse", "main" ],
                                         ["cat", "Sports: Spring Sports", "main" ] ],
	"/Sports/Spring Sports/M. Lacrosse" => [ ["tag", "M. Lacrosse", "main" ],
                                         ["cat", "Sports: Spring Sports", "main" ] ],
	"/Sports/Spring Sports/M. Tennis" => [ ["tag", "M. Tennis", "main" ],
                                         ["cat", "Sports: Spring Sports", "main" ] ],
	"/Opinion/Letters" => [ "cat", "Opinion: Letters", "main" ],
	"/Blogs/Cross Campus/Medicine" => [ "tag", "Medicine", "cross-campus" ],
	"/Blogs/Cross Campus/Hockey" => [ "tag", "Hockey", "cross-campus" ],
	"/WEEKEND/Doubletruck" => [ "cat", "Doubletruck", "weekend" ],
	"/WEEKEND/View" => [ "cat", "View", "weekend" ],
	"/WEEKEND/WEEKEND Cover" => [ "cat", "Cover", "weekend" ],
	"/WEEKEND/Backstage" => [ "cat", "Backstage", "weekend" ],
	"/WEEKEND/Interview" => [ "tag", "Interview", "weekend" ],
	"/WEEKEND/Art" => [ "cat", "Art", "weekend" ],
	"/WEEKEND/Column" => [ "cat", "Column", "weekend" ],
	"/Blogs/Cross Campus/Student Life" => [ "tag", "Student Life", "cross-campus" ],
	"/Blogs/Cross Campus/Arts" => [ "tag", "Arts", "cross-campus" ],
	"/News" => [ "", "", "main" ],
	"/Blogs/Cross Campus/Pundits" => [ "tag", "Pundits", "cross-campus" ],
	"/Blogs/Cross Campus/Yale College Council" => [ "tag", "Yale College Council", "cross-campus" ],
	"/News/Art News" => [ "cat", "Culture", "main" ],
	"/Sports/Winter Sports/M. Basketball" => [ [ "tag", "M. Basketball", "main" ],
                                             [ "cat", "Sports: Winter Sports", "main" ] ],
	"/Sports/Fall Sports/M. Golf" => [ [ "tag", "M. Golf", "main" ],
                                   [ "cat", "Sports: Fall Sports", "main" ] ],
  "/News/Sci-Tech News" => [ "cat", "Sci-Tech", "main" ],
	"/Blogs/Cross Campus/Alumni" => [ "tag", "Alumni", "cross-campus" ],
	"/Blogs/Cross Campus/Awards" => [ "tag", "Awards", "cross-campus" ],
	"/WEEKEND/Theater" => [ "cat", "Theater", "weekend" ],
	"/WEEKEND/TV" => [ "tag", "TV", "weekend" ],
	"/WEEKEND/Book" => [ "tag", "Book", "weekend" ],
	"/WEEKEND/Film" => [ "tag", "Film", "weekend" ],
	"/News/City/State Politics" => [ "tag", "State Politics", "main" ],
	"/Blogs/Cross Campus/Law" => [ "tag", "Law", "cross-campus" ],
	"/Blogs/Cross Campus/Residential Colleges" => [ "tag", "Residential Colleges", "cross-campus" ],
	"/Blogs/Cross Campus/Singapore" => [ "tag", "Singapore", "cross-campus" ],
	"/Blogs/Cross Campus/Social Media" => [ "tag", "Social Media", "cross-campus" ],
	"/Sports/Track" =>  [ [ "tag", "Track", "main" ],
                        [ "cat", "Sports", "main"] ],
	"/Blogs/Cross Campus/Religion" => [ "tag", "Religion", "cross-campus" ],
	"/Blogs/Cross Campus/In the News" => [ "tag", "In the News", "cross-campus" ],
	"/Blogs/Cross Campus/TV" => [ "tag", "TV", "cross-campus" ],
	"/Sports/W. Squash" => [ [ "tag", "W. Squash", "main" ],
                           [ "cat", "Sports", "main" ] ],
	"/Sports/Column" => [ [ "tag", "Column", "main" ],
                           [ "cat", "Sports", "main" ] ],
	"/Blogs/Cross Campus/Commencement" => [ "tag", "Commencement", "cross-campus" ],
	"/Blogs/Cross Campus/SOM" => [ "tag", "SOM", "cross-campus" ],
	"/Blogs/Cross Campus/International Affairs" => [ "tag", "International Affairs", "cross-campus" ],
	"/Blogs/Cross Campus/Admissions" => [ "tag", "Admissions", "cross-campus" ],
	"/Blogs/Cross Campus/Magazine" => [ "cat", "Magazine", "cross-campus" ],
	"/Blogs/Cross Campus/Famous People" => [ "tag", "Famous People", "cross-campus" ],
	"/WEEKEND/Scenic Views" => [ "tag", "Scenic Views", "weekend" ],
	"/Blogs/Cross Campus/University/Libraries" => [ "tag", "University Libraries", "cross-campus" ],
	"/Blogs/Cross Campus/Sexual Culture" => [ "tag", "Sexual Culture", "cross-campus" ],
	"/Blogs/Cross Campus/Race in America" => [ "tag", "Race in America", "cross-campus" ],
	"/Blogs/Cross Campus/Greek" => [ "tag", "Greek", "cross-campus" ],
	"/Blogs/Cross Campus/Ivy League" => [ "tag", "Ivy League", "cross-campus" ],
	"/Sports/Sailing" => [ [ "tag", "Sailing", "main" ],
                         [ "cat", "Sports", "main" ] ],
	"/Sports/Winter Sports/Fencing" => [ [ "cat", "Sports: Winter Sports", "main" ],
                                       [ "tag", "Fencing", "main"],
                                       [ "cat", "Sports", "main" ] ],
	"/Sports/Winter Sports/Gymnastics" => [ [ "cat", "Sports: Winter Sports", "main" ],
                                       [ "tag", "Gymnastics", "main"],
                                       [ "cat", "Sports", "main" ] ],
	"/Sports/Lacrosse" => [ [ "tag", "Lacrosse", "main" ],
                         [ "cat", "Sports", "main" ] ],
	"/Sports/Fall Sports/Football" => [ [ "cat", "Sports: Fall Sports", "main" ],
                                       [ "tag", "Football", "main"],
                                       [ "cat", "Sports", "main" ] ],
	"/Blogs/Cross Campus/Weird" => [ "tag", "Weird", "cross-campus" ],
	"/Magazine Pieces" => [ "", "", "magazine" ],
	"/Blogs/Cross Campus/Hartford" => [ "tag", "Hartford", "cross-campus" ],
	"/Blogs/Cross Campus/Economic Development" => [ "tag", "Economic Development", "cross-campus" ],
	"/Sports/Spring Sports" => [ "cat", "Sports: Spring Sports", "main" ],
	"/Sports/Winter Sports/M. Ice Hockey" => [ [ "cat", "Sports: Winter Sports", "main" ],
                                       [ "tag", "M. Ice Hockey", "main"],
                                       [ "cat", "Sports", "main" ] ],
	"/Blogs/Cross Campus/James Franco GRD '16" => [ "tag", "James Franco GRD '16", "cross-campus" ],
	"/Sports/Winter Sports/Swimming" => [ [ "cat", "Sports: Winter Sports", "main" ],
                                       [ "tag", "Swimming", "main"],
                                       [ "cat", "Sports", "main" ] ],
	"/Blogs/Cross Campus/Business" => [ "tag", "Business", "cross-campus" ],
	"/Blogs/Cross Campus/Connecticut" => [ "tag", "Connecticut", "cross-campus" ],
	"/Blogs/Cross Campus/Drama" => [ "tag", "Drama", "cross-campus" ],
	"/Blogs/Cross Campus/Basketball" => [ "tag", "Basketball", "cross-campus" ],
	"/Blogs/Cross Campus/Harvard" => [ "tag", "Harvard", "cross-campus" ],
	"/Sports/Hockey" => [ [ "tag", "Hockey", "main" ],
                        [ "cat", "Sports", "main" ] ],
	"/Blogs/Cross Campus/Men's Hockey" => [ "tag", "Men's Hockey", "cross-campus" ],
	"/Blogs/Cross Campus/Alcohol" => [ "tag", "Alcohol", "cross-campus" ],
	"/Blogs/Cross Campus/Sci-Tech" => [ "cat", "Sci-Tech", "cross-campus" ],
	"/Sports/M. Hockey" => [ [ "tag", "M. Hockey", "main" ],
                           [ "cat", "Sports", "main" ] ],
	"/Sports/W. Basketball" => [ [ "tag", "W. Basketball", "main" ],
                           [ "cat", "Sports", "main" ] ],
	"/Blogs/Cross Campus/Grad School" => [ "tag", "Grad School", "cross-campus" ],
	"/Sports/Football" => [ [ "tag", "Football", "main" ],
                           [ "cat", "Sports", "main" ] ],
	"/Blogs/Cross Campus/LGBT issues" => [ "tag", "LGBT issues", "cross-campus" ],
	"/Blogs/Cross Campus/Rankings" => [ "tag", "Rankings", "cross-campus" ],
	"/Blogs/Cross Campus/Environment" => [ "tag", "Environment", "cross-campus" ],
	"/Sports/Winter Sports/W. Basketball" => [ [ "cat", "Sports: Winter Sports", "main" ],
                                       [ "tag", "W. Basketball", "main"],
                                       [ "cat", "Sports", "main" ] ],
	"/Sports/Winter Sports/W. Squash" => [ [ "cat", "Sports: Winter Sports", "main" ],
                                       [ "tag", "W. Squash", "main"],
                                       [ "cat", "Sports", "main" ] ],
	"/Blogs/Cross Campus/Writing" => [ "tag", "Writing", "cross-campus" ],
	"/Magazine/Short Feature" => [ "cat", "Short Feature", "magazine" ],
	"/Magazine/Small Talk" => [ "cat", "Small Talk", "magazine" ],
	"/Magazine/Personal Essay" => [ "cat", "Personal Essay", "magazine" ],
	"/Magazine/Profile" => [ "cat", "Profile", "magazine" ],
	"/Magazine/Q's" => [ "cat", "Q's", "magazine" ],
	"/Magazine/Crit" => [ "cat", "Crit", "magazine" ],
	"/Magazine/Magazine Cover" => [ "cat", "Cover", "magazine" ],
	"/Magazine/Fiction" => [ "cat", "Fiction", "magazine" ],
	"/Sports/Winter Sports/W. Ice Hockey" => [ [ "cat", "Sports: Winter Sports", "main" ],
                                       [ "tag", "W. Ice Hockey", "main"],
                                       [ "cat", "Sports", "main" ] ],
	"/Sports/Winter Sports/M. Squash" => [ [ "cat", "Sports: Winter Sports", "main" ],
                                       [ "tag", "M. Squash", "main"],
                                       [ "cat", "Sports", "main" ] ],
	"/News/City/Business" => [ "tag", "Business", "main" ],
	"/Blogs/Cross Campus/Courts" => [ "tag", "Courts", "cross-campus" ],
	"/Blogs/Cross Campus/Research" => [ "tag", "Research", "cross-campus" ],
	"/Sports/Winter Sports/Indoor Track" => [ [ "cat", "Sports: Winter Sports", "main" ],
                                       [ "tag", "Indoor Track", "main"],
                                       [ "cat", "Sports", "main" ] ],
	"/Blogs/Cross Campus/Education" => [ "tag", "Education", "cross-campus" ],
	"/Blogs/Cross Campus/Sex Week" => [ "tag", "Sex Week", "cross-campus" ],
	"/Blogs/Cross Campus/Hazing" => [ "tag", "Hazing", "cross-campus" ],
	"/Blogs/Cross Campus/Love Week" => [ "tag", "Love Week", "cross-campus" ],
	"/Blogs/Cross Campus/Health" => [ "tag", "Health", "cross-campus" ],
	"/Blogs/Cross Campus/QPac" => [ "tag", "QPac", "cross-campus" ],
	"/News/Live Blog" => [ "", "", "main" ],
	"/News/University/Dining" => [ "tag", "Dining", "main" ],
	"/Blogs/Cross Campus/Gender" => [ "tag", "Gender", "cross-campus" ],
	"/News/University/Fourteen Colleges" => [ "tag", "Fourteen Colleges", "main" ],
	"/Sports/Winter Sports" => [ "cat", "Sports: Winter Sports", "main" ],
	"/Blogs/Cross Campus/Administration" => [ "tag", "Administration", "cross-campus" ],
	"/Blogs/Cross Campus/Expansion" => [ "tag", "Expansion", "cross-campus" ],
	"/Magazine/Poetry" => [ "cat", "Poetry", "magazine" ],
	"/Blogs/Cross Campus/Offensive" => [ "tag", "Offensive", "cross-campus" ],
	"/Magazine/Column" => [ "cat", "Column", "magazine" ],
	"/Blogs/Cross Campus/Lux et Securitas" => [ "tag", "Lux et Securitas", "cross-campus" ],
	"/Blogs/Cross Campus/Literature" => [ "tag", "Literature", "cross-campus" ],
	"/Blogs/Cross Campus/Modernism" => [ "tag", "Modernism", "cross-campus" ],
	"/Blogs/Cross Campus/Virginia Woolf" => [ "tag", "Virginia Woolf", "cross-campus" ],
	"/Blogs/Cross Campus/Partying, Partying, Yeah." => [ "tag", "Partying, Partying, Yeah.", "cross-campus" ],
	"/Blogs/Cross Campus/Fountains" => [ "tag", "Fountains", "cross-campus" ],
	"/Blogs/Cross Campus/Water" => [ "tag", "Water", "cross-campus" ],
	"/Blogs/Cross Campus/Endorsements" => [ "tag", "Endorsements", "cross-campus" ],
	"/Blogs/Cross Campus/Construction" => [ "tag", "Construction", "cross-campus" ],
	"/Blogs/Cross Campus/The Way We Live Now" => [ "tag", "The Way We Live Now", "cross-campus" ],
	"/Blogs/Cross Campus/Finance and Consulting" => [ "tag", "Finance and Consulting", "cross-campus" ],
	"/Blogs/Cross Campus/Snow!" => [ "tag", "Snow!", "cross-campus" ],
	"/Blogs/Cross Campus/Weather" => [ "tag", "Weather", "cross-campus" ],
	"/Blogs/Cross Campus/Tailgates" => [ "tag", "Tailgates", "cross-campus" ],
	"/News/Breaking" => [ "tag", "Breaking", "main" ],
	"/Blogs/Cross Campus/Soundbites" => [ "tag", "Soundbites", "cross-campus" ],
	"/Sports/W. Hockey" => [ "tag", "W. Hockey", "main" ],
	"/News/Academics" => [ "tag", "Academics", "main" ],
	"/Blogs/Cross Campus/Food" => [ "tag", "Food", "cross-campus" ],
	"/Blogs/Cross Campus/Froyo" => [ "tag", "Froyo", "cross-campus" ],
	"/Blogs/Cross Campus/Toads" => [ "tag", "Toads", "cross-campus" ],
	"/Blogs/Cross Campus/Shopping Period " => [ "tag", "Shopping Period ", "cross-campus" ],
	"/Blogs/Cross Campus/Crazy Stuff" => [ "tag", "Crazy Stuff", "cross-campus" ],
	"/Blogs/Cross Campus/Print Edition" => [ "tag", "Print Edition", "cross-campus" ],
	"/Blogs/Cross Campus/Dining " => [ "tag", "Dining ", "cross-campus" ],
	"/Blogs/Cross Campus/Concerts" => [ "tag", "Concerts", "cross-campus" ],
	"/Sports/The Game 2011" => [ "tag", "The Game 2011", "main" ],
	"/Blogs/Yale Sports Liveblog" => [ "", "", "main" ],
	"/WEEKEND/Living" => [ "tag", "Living", "weekend" ],
	"/Magazine/Non-Fiction" => [ "cat", "Non-Fiction", "magazine" ],
	"/Sports/Fall Sports/Volleyball" => [ ["cat", "Sports", "main" ],
                                        ["cat", "Sports: Fall Sports", "main"],
                                        ["tag", "Volleyball", "main"] ],
	"/Sports/Fall Sports/W. Soccer" => [ ["cat", "Sports", "main" ],
                                        ["cat", "Sports: Fall Sports", "main"],
                                        ["tag", "W. Soccer", "main"] ],
	"/Sports/Fall Sports/Field Hockey" => [ ["cat", "Sports", "main" ],
                                        ["cat", "Sports: Fall Sports", "main"],
                                        ["tag", "Field Hockey", "main"] ],
	"/Sports/Fall Sports/M. Soccer" => [ ["cat", "Sports", "main" ],
                                        ["cat", "Sports: Fall Sports", "main"],
                                        ["tag", "M. Soccer", "main"] ],
	"/Sports/Fall Sports/Cross Country" => [ ["cat", "Sports", "main" ],
                                        ["cat", "Sports: Fall Sports", "main"],
                                        ["tag", "Cross Country", "main"] ],
	"/News/City/Crime" => [ "tag", "Crime", "main" ],
	"/Sports/M. Baseball" => [ [ "tag", "M. Baseball", "main" ],
                             [ "cat", "Sports", "main" ] ],
	"/Sports/Women's" => [ "", "", "main" ],
	"/Blogs/Cross Campus/Apple Store" => [ "tag", "Apple Store", "cross-campus" ],
	"/Blogs/Cross Campus/Irene" => [ "tag", "Irene", "cross-campus" ],
	"/Blogs/Cross Campus/Election 2011" => [ "tag", "Election 2011", "cross-campus" ],
	"/Magazine/Advice Column" => [ "tag", "Advice Column", "magazine" ],
	"/Blogs/Cross Campus/ROTC " => [ "tag", "ROTC ", "cross-campus" ],
	"/Blogs/Cross Campus/DKE" => [ "tag", "DKE", "cross-campus" ],
	"/Sports/M. Football" => [ [ "tag", "M. Football", "main" ],
                             [ "cat", "Sports", "main" ] ],
	"/Blogs/Scene Blog" => [ "tag", "Scene", "main" ],
	"/Opinion/Illustrations" => [ "", "", "main" ],
	"/Opinion/Comics" => [ "cat", "Opinion: Comics", "main" ],
	"/Sports/Sports Opinion" => [ [ "tag", "Sports Opinion", "main" ],
                                [ "cat", "Sports", "main" ] ],
	"/Sports/Basketball" => [ [ "tag", "Basketball", "main" ],
                                [ "cat", "Sports", "main" ] ],
	"/Sports/W. Swimming" => [ [ "tag", "W. Swimming", "main" ],
                                [ "cat", "Sports", "main" ] ],
	"/Sports/M. Squash" => [ [ "tag", "M. Squash", "main" ],
                                [ "cat", "Sports", "main" ] ],
	"/Sports/Squash" => [ [ "tag", "Squash", "main" ],
                                [ "cat", "Sports", "main" ] ],
	"/Sports/M. Swimming" => [ [ "tag", "M. Swimming", "main" ],
                                [ "cat", "Sports", "main" ] ],
	"/Blogs/News/Art News" => [ "cat", "Culture", "cross-campus" ],
	"/Blogs/China 100 Blog" => [ "tag", "China 100 Blog", "cross-campus" ],
	"/Scene/Art" => [ "tag", "Scene: Art", "main" ],
	"/Scene/Interview" => [ "tag", "Scene: Interview", "main" ],
	"/News/Sci/Tech News" => [ "cat", "Sci/Tech", "main" ],
	"/News/Sci" => [ "cat", "Sci/Tech", "main" ],
	"/News/University/Master's Teas" => [ "tag", "Master's Teas", "main" ],
	"/News/Up Close" => [ "tag", "Up Close", "main" ],
	"/News/Business News" => [ "tag", "Business News", "main" ],
	"/Sports/Sports General" => [ "cat", "Sports", "main" ],
	"/WEEKEND/This Week" => [ "tag", "This Week", "weekend" ],
	"/Sports/Ice" => [ "cat", "Sports", "main" ],
	"/Sports/W." => [ "cat", "Sports", "main" ],
	"/Sports/Field" => [ "cat", "Sports", "main" ],
	"/Blogs/News" => [ "cat", "News", "cross-campus" ],
	"/Scene/Living" => [ "tag", "Living", "weekend" ],
	"/Scene/Music" => [ "tag", "Music", "weekend" ],
	"/Sports/Fall Sports" => [ "cat", "Sports: Fall Sports", "main" ],
	"/Scene/Scenic Views" => [ "tag", "Scenic Views", "weekend" ],
	"/Scene/Scene Cover" => [ "tag", "Scene Cover", "weekend" ],
	"/Blogs/Sports/Sports General" => [ "tag", "Sports", "cross-campus" ],
	"/Sports/W. Baseball" => [ [ "tag", "W. Baseball", "main" ],
                             [ "cat", "Sports", "main"] ],
	"/Sports/Men's" => [ "cat", "Sports", "main" ],
	"/Sports/Harvard-Yale 2009" => [ "tag", "Harvard-Yale 2009", "main" ],
	"/Opinion/Corrections" => [ "tag", "Opinion Corrections", "main" ],
	"/Scene/Theater" => [ "cat", "Theater", "weekend" ],
	"/Scene/Film" => [ "tag", "Film", "weekend" ],
	"/Blogs/Yale on the Trail" => [ "tag", "Yale on the Trail", "cross-campus" ],
	"/Blogs/Yale on the Trail/Battlegrounds" => [ "tag", "Yale on the Trail: Battlegrounds", "cross-campus" ],
	"/Blogs/Yale on the Trail/Washington DC" => [ "tag", "Yale on the Trail: Washington DC", "cross-campus" ],
	"/Blogs/Yale on the Trail/Barack Obama" => [ "tag", "Yale on the Trail: Barack Obama", "cross-campus" ],
	"/Blogs/Yale on the Trail/Democrats" => [ "tag", "Yale on the Trail: Democrats", "cross-campus" ],
	"/Blogs/Yale on the Trail/Inauguration" => [ "tag", "Yale on the Trail: Inauguration", "cross-campus" ],
	"/Blogs/Yale on the Trail/Connecticut" => [ "tag", "Yale on the Trail: Connecticut", "cross-campus" ],
	"/Blogs/Yale on the Trail/Joe Lieberman" => [ "tag", "Yale on the Trail: Joe Lieberman", "cross-campus" ],
	"/Blogs/Yale on the Trail/John McCain" => [ "tag", "Yale on the Trail:John McCain", "cross-campus" ],
	"/Blogs/Yale on the Trail/Yale on the Trail" => [ "tag", "Yale on the Trail", "cross-campus" ],
	"/Blogs/Yale Sports Liveblog/Live Blog" => [ "tag", "Yale Sports Liveblog: Live Blog", "cross-campus" ],
	"/Blogs/Yale on the Trail/Chicago" => [ "tag", "Yale on the Trail: Chicago", "cross-campus" ],
	"/Blogs/Yale on the Trail/Virginia" => [ "tag", "Yale on the Trail: Virginia", "cross-campus" ],
	"/Blogs/Yale on the Trail/Arizona" => [ "tag", "Yale on the Trail: Arizona", "cross-campus" ],
	"/Blogs/Yale on the Trail/Scott Kleeb" => [ "tag", "Yale on the Trail: Scott Kleeb", "cross-campus" ],
	"/Blogs/Yale on the Trail/Nebraska" => [ "tag", "Yale on the Trail: Nebraska", "cross-campus" ],
	"/Blogs/Yale on the Trail/Republicans" => [ "tag", "Yale on the Trail: Republicans", "cross-campus" ],
	"/Blogs/Yale on the Trail/Democratic National Convention" => [ "tag", "Yale on the Trail: Democratic National Convention", "cross-campus" ],
	"/Blogs/Yale on the Trail/Hillary Clinton" => [ "tag", "Yale on the Trail: Hillary Clinton", "cross-campus" ],
	"/Blogs/Yale on the Trail/The Youth Vote" => [ "tag", "Yale on the Trail: The Youth Vote", "cross-campus" ],
	"/Blogs/Yale on the Trail/Student Activism" => [ "tag", "Yale on the Trail: Student Activism", "cross-campus" ],
	"/Blogs/Yale on the Trail/Study Break" => [ "tag", "Yale on the Trail: Study Break", "cross-campus" ],
	"/Blogs/Inside the Dragon" => [ "tag", "Inside the Dragon", "cross-campus" ],
	"/Blogs/NewsFeed" => [ "tag", "NewsFeed", "cross-campus" ],
	"/Blogs/Yale Decides 2008" => [ "tag", "Yale Decides 2008", "cross-campus" ],
	"/Blogs/NewsFeed/Reviews" => [ "tag", "NewsFeed: Reviews", "cross-campus" ],
	"/Blogs/NewsFeed/Top 10" => [ "tag", "NewsFeed: Top 10", "cross-campus" ],
	"/Blogs/NewsFeed/Skip the Club" => [ "tag", "NewsFeed: Skip the Club", "cross-campus" ],
	"/Blogs/NewsFeed/Abroad" => [ "tag", "NewsFeed: Abroad", "cross-campus" ],
	"/Blogs/NewsFeed/Turkish Taste" => [ "tag", "NewsFeed: Turkish Taste", "cross-campus" ],
	"/Blogs/Yale on the Trail/Ron Paul" => [ "tag", "Yale on the Trail: Ron Paul", "cross-campus" ],
	"/Blogs/Yale on the Trail/Chris Dodd" => [ "tag", "Yale on the Trail: Chris Dodd", "cross-campus" ],
	"/Blogs/Yale on the Trail/Mitt Romney" => [ "tag", "Yale on the Trail: Mitt Romney", "cross-campus" ],
	"/Blogs/Yale on the Trail/Iowa" => [ "tag", "Yale on the Trail: Iowa", "cross-campus" ],
	"/Blogs/Yale on the Trail/New Hampshire" => [ "tag", "Yale on the Trail: New Hampshire", "cross-campus" ],
	"/Blogs/Yale on the Trail/Independents" => [ "tag", "Yale on the Trail: Independents", "cross-campus" ],
	"/Blogs/Yale on the Trail/Mike Huckabee" => [ "tag", "Yale on the Trail: Mike Huckabee", "cross-campus" ],
	"/Blogs/Yale on the Trail/John Edwards" => [ "tag", "Yale on the Trail: John Edwards", "cross-campus" ],
	"/Blogs/Yale on the Trail/Demographics" => [ "tag", "Yale on the Trail: Demographics", "cross-campus" ],
	"/Blogs/Yale on the Trail/Mike Gravel" => [ "tag", "Yale on the Trail: Mike Gravel", "cross-campus" ],
	"/Blogs/Yale on the Trail/Rudy Giuliani" => [ "tag", "Yale on the Trail: Rudy Giuliani", "cross-campus" ],
	"/Blogs/Yale on the Trail/Bill Richardson" => [ "tag", "Yale on the Trail: Bill Richardson", "cross-campus" ],
	"/Blogs/Yale on the Trail/Black Vote" => [ "tag", "Yale on the Trail: Black Vote", "cross-campus" ],
	"/Blogs/Yale on the Trail/Fred Thompson" => [ "tag", "Yale on the Trail: Fred Thompson", "cross-campus" ],
	"/Blogs/Yale on the Trail/Joe Biden" => [ "tag", "Yale on the Trail: Joe Biden", "cross-campus" ],
	"/Blogs/Yale on the Trail/Hispanic Vote" => [ "tag", "Yale on the Trail: Hispanic Vote", "cross-campus" ],
	"/Blogs/Scene&heard" => [ "tag", "Scene&heard", "weekend" ],
	"/Blogs/Scene&heard/Written by Jenny Burke" => [ "", "", "main" ],
	"/Blogs/Scene&heard/Album Review" => [ "tag", "Album Review", "weekend" ],
	"/Blogs/Scene&heard/Written by Nathan Harden" => [ "", "", "weekend" ],
	"/Blogs/Scene&heard/Concert Review" => [ "tag", "Concert Review", "weekend" ],
	"/Blogs/Scene&heard/Written by Melissa Leon" => [ "", "", "weekend" ],
	"/Blogs/Scene&heard/Rock" => [ "tag", "Rock", "weekend" ],
	"/Blogs/Scene&heard/Written by Nicolas Niarchos" => [ "", "", "weekend" ],
	"/Blogs/Scene&heard/Written by Anna Pitoniak" => [ "", "", "weekend" ],
	"/Blogs/Scene&heard/Electronic" => [ "tag", "Electronic", "weekend" ],
	"/Blogs/Scene&heard/Scenic Interview" => [ "tag", "Scenic Interview", "weekend" ],
	"/Blogs/Scene&heard/Written by Rebecca Arzoian" => [ "", "", "weekend" ],
	"/Blogs/Scene&heard/Written by June Torbati" => [ "", "", "weekend" ],
	"/Blogs/Scene&heard/Indie" => [ "tag", "Indie", "weekend" ],
	"/Blogs/Scene&heard/Written by Ben Beitler" => [ "", "", "weekend" ],
	"/Blogs/Scene&heard/Written by Sarah Wolf" => [ "", "", "weekend" ],
	"/Blogs/Scene&heard/Written by Amanda Glassman" => [ "", "", "weekend" ],
	"/Blogs/Scene&heard/Hip Hop" => [ "tag", "Hip Hop", "weekend" ],
	"/Blogs/Scene&heard/Song Review" => [ "tag", "Song Review", "main" ],
	"/Blogs/Scene&heard/Written by Will Alden" => [ "", "", "weekend" ],
	"/Blogs/Scene&heard/Written by Meredith Hitchcock" => [ "", "", "weekend" ],
	"/Blogs/Scene&heard/Written by Justin Jannise" => [ "", "", "weekend" ],
	"/Blogs/China 100 Blog/China" => [ "tag", "China 100 Blog", "cross-campus" ],
	"/Scene/This Week" => [ "tag", "Scene: This Week", "weekend" ],
	"/Scene/TV" => [ "tag", "TV", "weekend" ],
	"/Scene/Book" => [ "tag", "Book", "weekend" ],
	"/Scene/Performance" => [ "tag", "Performance", "weekend" ],
	"/Magazine/Horoscopes" => [ "tag", "Horoscopes", "magazine" ],
	"/Magazine/Best of New Heaven" => [ "tag", "Best of New Haven", "magazine" ],
}
